"""baseline v0.1.0

Revision ID: 93b4854ea697
Revises: 
Create Date: 2026-01-01 16:11:55.191190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
from pgvector.sqlalchemy import Vector
import pgvector.sqlalchemy.vector
# revision identifiers, used by Alembic.
revision: str = '93b4854ea697'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('incident_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('affected_sys', sa.Text(), nullable=True),
    sa.Column('reporter', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_raw', sa.Text(), nullable=False),
    sa.Column('message_redacted', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('embedding_version', sa.Integer(), nullable=True),
    sa.Column('embedding_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_logs_created_at'), 'incident_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_logs_embedding_status'), 'incident_logs', ['embedding_status'], unique=False)
    op.create_index(op.f('ix_incident_logs_id'), 'incident_logs', ['id'], unique=False)
    op.create_index(op.f('ix_incident_logs_is_deleted'), 'incident_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_incident_logs_reporter'), 'incident_logs', ['reporter'], unique=False)
    op.create_index(op.f('ix_incident_logs_service'), 'incident_logs', ['service'], unique=False)
    op.create_index(op.f('ix_incident_logs_severity'), 'incident_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_incident_logs_source'), 'incident_logs', ['source'], unique=False)
    op.create_index('ix_incident_logs_tenant_created', 'incident_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_incident_logs_tenant_id'), 'incident_logs', ['tenant_id'], unique=False)
    op.create_index('ix_incident_logs_tenant_service', 'incident_logs', ['tenant_id', 'service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_logs_tenant_service', table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_tenant_id'), table_name='incident_logs')
    op.drop_index('ix_incident_logs_tenant_created', table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_source'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_severity'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_service'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_reporter'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_is_deleted'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_id'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_embedding_status'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_created_at'), table_name='incident_logs')
    op.drop_table('incident_logs')
    # ### end Alembic commands ###
